name: flutter_01
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
     sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
     flutter:
          sdk: flutter
     # The following adds the Cupertino Icons font to your application.
     # Use with the CupertinoIcons class for iOS style icons.
     cupertino_icons: ^1.0.2
     url_launcher: ^6.1.11
     youtube_player_flutter: ^8.1.2
     youtube_player_iframe: ^4.0.4
     page_transition: ^2.0.9
dev_dependencies:
     flutter_test:
          sdk: flutter

     # The "flutter_lints" package below contains a set of recommended lints to
     # encourage good coding practices. The lint set provided by the package is
     # activated in the `analysis_options.yaml` file located at the root of your
     # package. See that file for information about deactivating specific lint
     # rules and activating additional ones.
     flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

     # The following line ensures that the Material Icons font is
     # included with your application, so that you can use the icons in
     # the material Icons class.
     uses-material-design: true

     # To add assets to your application, add an assets section, like this:
     assets:
          - image/LoGo.png
          - image/trangchu/1.jpg
          - image/trangchu/2.jpg
          - image/trangchu/3.webp
          - image/trangchu/4.jpg
          - image/trangchu/5.jpg
          - image/trangchu/6.jpg
          - image/trangchu/7.jpg
          - image/CungDinh/0.jpg
          - image/CungDinh/1.jpg
          - image/CungDinh/2.jpg
          - image/CungDinh/3.jpg
          - image/CungDinh/4.jpg
          - image/CungDinh/5.jpg
          - image/CungDinh/6.jpg
          - image/CungDinh/7.jpg
          - image/CungDinh/8.jpg
          - image/CungDinh/9.jpg
          - image/CungDinh/10.jpg
          - image/CungDinh/11.jpg
          - image/CungDinh/12.jpg
          - image/CungDinh/13.jpg
          - image/CungDinh/14.jpg
          - image/CungDinh/15.jpg
          - image/CungDinh/16.jpg
          - image/CungDinh/18.jpg
          - image/CungDinh/19.jpg
          - image/CungDinh/20.jpg
          - image/CungDinh/21.jpg
          - image/CungDinh/22.jpg
          - image/CungDinh/23.jpg
          - image/AoNguThan/1.jpg
          - image/AoNguThan/2.jpg
          - image/AoNguThan/3.jpg
          - image/AoNguThan/4.jpg
          - image/AoNguThan/5.jpg
          - image/AoNguThan/6.jpg
          - image/AoNguThan/44.jpg
          - image/AoNguThan/7.jpg
          - image/LichSuAoDai/1.jpg
          - image/LichSuAoDai/2.jpg
          - image/LichSuAoDai/3.jpg
          - image/LichSuAoDai/4.jpg
          - image/LongBao/1.jpg
          - image/LongBao/2.jpg
          - image/LongBao/3.jpg
          - image/LongBao/4.jpg
          - image/LongBao/5.jpg
          - image/LongBao/6.jpg
          - image/LongBao/7.jpg
          - image/LongBao/8.jpg
          - image/LongBao/9.jpg
          - image/LongBao/10.jpg
          - image/LongBao/11.jpg
          - image/LongBao/12.jpg
          - image/LongBao/13.jpg
          - image/LongBao/14.jpg
          - image/CuaHang/1.jpg
          - image/CuaHang/2.jpg
          - image/CuaHang/3.jpg
          - image/CuaHang/4.jpg
          - image/CuaHang/5.jpg
          - image/CuaHang/6.jpg
          - image/CuaHang/7.jpg
          - image/CuaHang/8.jpg
          - image/LeHoi/1.jpg
          - image/LeHoi/2.jpg
          - image/LeHoi/3.jpg
          - image/LeHoi/4.jpg
          - image/LeHoi/5.jpg
          - image/LeHoi/6.jpg
          - image/LeHoi/7.jpg
          - image/LeHoi/8.jpg
          - image/LeHoi/9.jpg
          - image/LeHoi/10.jpg
          - image/LeHoi/81.jpg
          - image/LeHoi/82.jpg
          - image/LeHoi/83.jpg
          - image/LeHoi/11.jpg
          - image/nenmacaodai/1.jpg
          - image/nenmacaodai/2.jpg
          - image/nenmacaodai/3.jpg
          - image/nenmacaodai/4.jpg
          - image/nenmacaodai/5.jpg
          - image/nenmacaodai/6.jpg
          - image/nenmacaodai/7.jpg
          - image/nenmacaodai/8.jpg
          - image/nenmacaodai/9.jpg
          - image/nenmacaodai/10.jpg
          - image/nenmacaodai/11.jpg
          - image/nenmacaodai/12.jpg
          - image/VaiMay/1.jpg
          - image/VaiMay/2.jpg
          - image/VaiMay/3.jpg
          - image/VaiMay/4.jpg
          - image/VaiMay/5.jpg
          - image/VaiMay/6.jpg
          - image/VaiMay/7.jpg
          - image/VaiMay/8.jpg
          - image/VaiMay/9.jpg
          - image/VaiMay/10.jpg
          - image/VaiMay/11.jpg
          - image/VaiMay/12.jpg
          - image/VaiMay/13.jpg
          - image/VaiMay/14.jpg
          - image/VaiMay/15.jpg
          - image/VaiMay/16.jpg
          - image/VaiMay/17.jpg
          - image/VaiMay/18.jpg
          - image/VaiMay/19.jpg
          - image/VaiMay/20.jpg
          - image/ChupAnhAD/1.jpg
          - image/ChupAnhAD/2.jpg
          - image/ChupAnhAD/3.jpg
          - image/ChupAnhAD/4.jpg
          - image/ChupAnhAD/5.jpg
          - image/ChupAnhAD/6.jpg
          - image/ChupAnhAD/7.jpg
          - image/ChupAnhAD/8.jpg
          - image/ChupAnhAD/9.jpg
          - image/ChupAnhAD/10.jpg
          - image/ChupAnhAD/11.jpg
          - image/ChupAnhAD/12.jpg
          - image/ChupAnhAD/13.jpg
          - image/ChupAnhAD/14.jpg
          - image/ChupAnhAD/15.jpg
          - image/ChupAnhAD/16.jpg
          - image/ChupAnhAD/17.jpg
          - image/ChupAnhAD/18.jpg
          - image/ChupAnhAD/19.jpg
          - image/ChupAnhAD/20.jpg
          - image/ChupAnhAD/21.jpg
          - image/ChupAnhAD/22.jpg
          - image/ChupAnhAD/23.jpg
          - image/ChupAnhAD/24.jpg
          - image/ChupAnhAD/25.jpg
          - image/ChupAnhAD/26.jpg
          - image/ChupAnhAD/27.jpg
          - image/ChupAnhAD/28.jpg
          - image/ChupAnhAD/29.jpg
          - image/ChupAnhAD/30.jpg
          - image/ChupAnhAD/31.jpg
          - image/ChupAnhAD/32.jpg
          - image/ChupAnhAD/33.jpg
          - image/ChupAnhAD/34.jpg
          - image/AoNhatBinh/1.jpg
          - image/AoNhatBinh/2.jpg
          - image/AoNhatBinh/3.jpg
          - image/AoNhatBinh/4.jpg
          - image/AoNhatBinh/5.jpg
          - image/AoNhatBinh/6.jpg
          - image/AoNhatBinh/7.jpg
          - image/AoNhatBinh/8.jpg
          - image/AoNhatBinh/55.jpg
          - image/AoNhatBinh/9.jpg
          - image/AoNhatBinh/10.jpg
          - image/AoNhatBinh/11.jpg
          - image/AoNhatBinh/12.jpg
          - image/AoNhatBinh/13.jpg
          - image/AoNhatBinh/14.jpg
          - image/PhuKien/01.jpg
          - image/PhuKien/1.jpg
          - image/PhuKien/2.jpg
          - image/PhuKien/3.jpg
          - image/PhuKien/4.jpg
          - image/PhuKien/5.jpg
          - image/PhuKien/6.jpg
          - image/PhuKien/7.jpg
          - image/PhuKien/8.jpg
          - image/PhuKien/9.jpg
          - image/PhuKien/10.jpg
          - image/PhuKien/11.jpg
          - image/PhuKien/12.jpg
          - image/PhuKien/13.jpg
          - image/PhuKien/14.jpg
          - image/PhuKien/15.jpg
          - image/PhuKien/16.jpg
          - image/PhuKien/17.jpg
          - image/PhuKien/18.jpg
          - image/PhuKien/19.jpg
          - image/PhuKien/20.jpg
          - image/PhuKien/21.jpg
          - image/PhuKien/22.jpg
          - image/PhuKien/23.jpg
          - image/PhuKien/24.jpg
          - image/PhuKien/25.jpg










     # An image asset can refer to one or more resolution-specific "variants", see
     # https://flutter.dev/assets-and-images/#resolution-aware

     # For details regarding adding assets from package dependencies, see
     # https://flutter.dev/assets-and-images/#from-packages

     # To add custom fonts to your application, add a fonts section here,
     # in this "flutter" section. Each entry in this list should have a
     # "family" key with the font family name, and a "fonts" key with a
     # list giving the asset and other descriptors for the font. For
     # example:
     # fonts:
     #   - family: Schyler
     #     fonts:
     #       - asset: fonts/Schyler-Regular.ttf
     #       - asset: fonts/Schyler-Italic.ttf
     #         style: italic
     #   - family: Trajan Pro
     #     fonts:
     #       - asset: fonts/TrajanPro.ttf
     #       - asset: fonts/TrajanPro_Bold.ttf
     #         weight: 700
     #
     # For details regarding fonts from package dependencies,
     # see https://flutter.dev/custom-fonts/#from-packages
